version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3100:3100"
    environment:
      - PORT=3100
      - MONGODB_URI=mongodb://mongodb:27017/books
      - REDIS_URI=redis://redis:6379
      - RABBITMQ_URI=amqp://rabbitmq:5672
    depends_on:
      - mongodb
      - redis
      - rabbitmq
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  redis:
    image: redislabs/redistimeseries:edge
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --loadmodule /usr/lib/redis/modules/redistimeseries.so
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
  rabbitmq_data:
